version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      MYSQL_DATABASE: db_name
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_pass
    restart: always
    networks:
      - frontend
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: mysql_root_pass
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user_name
      WORDPRESS_DB_PASSWORD: user_pass
      WORDPRESS_TABLE_PREFIX: wp_
    restart: always
    networks:
      - frontend
  nginx:
    image: nginx:alpine
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wp-data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
volumes:
  db-data:
    external: true
  wp-data:
    external: true