version: '3'
#TODO faudra que les volumes soit dans /home/login/data
services:
  mysql:
    build: ./requirements/mariadb/
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - frontend
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - wp-data:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
    restart: always
    networks:
      - frontend
  nginx:
    build: ./requirements/nginx/
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wp-data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - frontend
networks:
  frontend:
    driver: bridge
volumes:
  db-data:
    external: true
  wp-data:
    external: true