version: '3'
services:
  mysql:
    image: mariadb
    volumes:
      -
    environment:
      - 
    restart: always
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      -
    depends_on:
      - mysql
    environment:
      - 
    links: mysql
    restart: always
  nginx:
    image: nginx:alpine
    volumes:
      -
    ports:
      - 8080:80
    links: wordpress 
